### ISSUE TITLE
Update protocol definitions to include mosaic layouts

### ISSUE THREAD

**Issue by acazacu** [googleapis/nodejs-monitoring-dashboards#149]
**Is your feature request related to a problem? Please describe.**

The protocol definition implemented in the library does not match the RPC protocol made public and documented by Google. The protocol implemented by the library is missing the MosaicLayout definition.

Please update the library to implement the latest version of the protocol definition, as it is [documented](https://cloud.google.com/monitoring/api/ref_v3/rpc/google.monitoring.dashboard.v1#google.monitoring.dashboard.v1.MosaicLayout) and [published](https://github.com/googleapis/googleapis/tree/master/google/monitoring/dashboard/v1) by Google.

 **Describe alternatives you've considered**

1. Using the REST API (prior to [googleapis/googleapis](https://github.com/googleapis/googleapis) having been [updated](https://github.com/googleapis/googleapis/commit/0dafa3963ef6fcb8a7f5daaa4bec12adb04de518)).

2. Generating an RPC client from the [googleapis](https://github.com/googleapis/googleapis) [monitoring dashboards protocol definitions](https://github.com/googleapis/googleapis/tree/master/google/monitoring/dashboard/v1).

**Comment by sofisl** [comment]
After a quick internal fix, this should be resolved tomorrow.

**Comment by acazacu** [comment]
@sofisl Thank you for the fast response, really looking forward to switching to the RPC API!

**Comment by sofisl** [comment]
All set! See #152
